### ISSUE TITLE
Create env feature

### ISSUE THREAD

**Issue by khorolets** [gtalarico/pipenv-pipes#13]
I hope I'm not the only one who switches between environments by navigating to my project directories (`.env`). So the most often usecase is to create an environment.

`virualenvwrapper` has the feature to create env and connect it with a project dir. 

Have you any plans to deliver such sort of action to your project?

Thanks.

P.S. Nice job, thank you for your work!

**Comment by gtalarico** [comment]
Hi @khorolets 
Pipes is not an environment manager, but Pipenv is.
Pipes is designed to work alongside Pipenv, so if you are not using it yet I suggest you check out the [documentation](https://docs.pipenv.org/)

Once an environment is created with Pipenv, you can use Pipes quickly switch between your Pipenv project directories and enviroments.
