### ISSUE TITLE
Deletion of Environments

### ISSUE THREAD

**Issue by Immortalin** [gtalarico/pipenv-pipes#21]
**Is your feature request related to a problem? Please describe.**
It would be great if we can delete envs directly from Pipes

**Describe the solution you'd like**
A key combination to trigger a deletion prompt i.e. yes/no/okay/cancel 
Pipenvs are not particularly important as they can be recreated rather easily so accidental deletions is not that big of a deal.

**Describe alternatives you've considered**
Doing it manually, not feasible for large number of envs.

**Comment by gtalarico** [comment]
This would be great. Are you interested in submitting a PR?

Probably something like:
`pipes {query/envname} --delete`

If one match:
`Are you sure you want to delete the environment 'xxx-123x' ? [y/N]`

If none or multiple matches, launch env selector UI, or reject and ask for a more specific name....

**Comment by Immortalin** [comment]
How do you develop and test this? Especially since you can't do it from inside a pipenv

**Comment by gtalarico** [comment]
The suite includes fixtures that creates 2 temp environments for tests to run on (proj1 and proj2)
I would implement the delete functionality in `core.delete_enviroment(envpath)` something like this:

``` 
def delete_environnment(envpath):
     # ...
     shutil.rmtree(envpath)
     # Might need to wait for deletion to complete sine envs have many files
     # see stackoverflow 21505313
     # ...
```
And then do 2 tests.

### Unit:
Test `delete_environment` function and ensure target test envs is deleted

```python

    def test_delete_env(self, mock_env_home):
        # get first test env
        pipenv_home, mock_projects_dir = mock_env_home
        envname = os.listdir(pipenv_home)[0]
        envpath = os.path.join(pipenv_home, envname)

        assert os.path.exists(envpath)
        delete_environment() # delete_env is helper function to delete env
        assert not os.path.exists(envpath)      
```

### Integration Test
```python
    def test_cli_delete_env(runner):
        # Call delete command
        result = runner.invoke(
            pipes, args=['proj1 --delete'], catch_exceptions=False)
        assert result.exit_code == 0
        # Call delete command
        result = runner.invoke(
            pipes, args=['--list'], catch_exceptions=False)
        assert result.exit_code == 0
        # Assert deleted test env proj1 no longer exists
        assert 'proj1' not in result.output 
```

**Comment by Immortalin** [comment]
No what I mean is how do you run this while developing? I am getting `__version__` errors when I try to run `python CLI.py`
