### ISSUE TITLE
Shell Completion OpenBSD (pd)ksh

### ISSUE THREAD

**Issue by hucste** [gtalarico/pipenv-pipes#29]
On OpenBSD, we've by default the pdksh. 

To have a shell completion, write into your personal "~/.profile": 
```
# after the call of exported environments variables for your Python, as WORKON_HOME.
set -A complete_pipes -- $(pipes --_completion)
```
Restart your session or a new terminal ;)

**Comment by gtalarico** [comment]
Happy to merge if you could add the info here:
https://github.com/gtalarico/pipenv-pipes/blob/master/docs/completions.rst

**Comment by hucste** [comment]
see #30 :p

**Comment by gtalarico** [comment]
merged
