### ISSUE TITLE
pipes activation does not cd to venv .project path

### ISSUE THREAD

**Issue by cometsong** [gtalarico/pipenv-pipes#31]
**Describe the bug**
From docs: 
>   "This would cd into directory /path/to/project1 and activate the corresponding Pipenv Shell."

in the section:
    https://pipenv-pipes.readthedocs.io/en/latest/usage.html#from-the-command-line

**To Reproduce**
1. Use `pipenv install` to create new venv in ~/code/path/proj1 (sample shown below)
2. In that project dir, type `pipes --link .`, success: *Project Directory Set*.
3. `cd /some/where/else/`
4. `pipes -v proj1`

**Expected behavior**
The docs say that `pipes` will cd into the *project directory* and then `activate` it.
It activates it, but then I'm in my `$HOME` directory, as happens when using `cd` and have no path arg following. 
It does *show* the "Project Directory" correctly, which *is* in the `.project` file within the `pipenv --venv` folder as expected.... but doens't `cd` to it at all.

**Screenshots**
`--list`
![Screen Shot 2019-08-08 at 10 17 00](https://user-images.githubusercontent.com/307777/62710809-f6b0f980-b9c5-11e9-9641-18ee5e6283e7.png)
`--verbose envname`
![Screen Shot 2019-08-08 at 10 17 26](https://user-images.githubusercontent.com/307777/62711109-7ccd4000-b9c6-11e9-8171-c21daded5fbf.png)

**Environment:**
 - OS: *Darwin Kernel Version 18.5.0*
 - Pipes Version: *0.7.1*
- Shell: *Bash v5.0*

**Comment by cometsong** [comment]
Now I've discovered `pipenv shell` does the same thing.  😞 

So maybe the problem is with that app or setup of it... ?

**Comment by cometsong** [comment]
Horribly my fault on this one!
I have a script that runs different setup with aliases and commands for each different server work on... and this ran *after* the venv was activated.
Closing and hanging shamefaced. 🙁

**Comment by gtalarico** [comment]
thanks for reporting back
